POST http://localhost:9000/orders/ HTTP/1.1
content-type: application/json

{ 
   "orderDetails": [
      {
         "productId": "641f1574c17b67a77ef826e1",
         "price": 20,
         "discount": 5,
         "quantity": 2,
         "description": "Polo shirt"
      }
   ],
   "createdDate": "2023/04/05",
   "shippedDate": "2023/05/05",
   "paymentType": "CASH",
   "shippingAddress": "38 Yên Bái",
   "status": "CANCELED",
   "description": "Polo shirt",
   "customerId": "642432c529872aa9280f22df",
   "employeeId": "642d7c28d929e7035b4806c2"
}