POST http://localhost:9000/employees HTTP/1.1
content-type: application/json

{
    "firstName": "Lan",
    "lastName": "Nguyễn Thị",
    "email": "nguyenthilan@gmail.com",
    "password": "111111",
    "phoneNumber": "0337214789",
    "address": "22 Nguyên Văn Linh",
    "birthday": "1999/02/14"
}