POST http://localhost:9000/employees HTTP/1.1
content-type: application/json

{
    "firstName": "Pa",
    "lastName": "Lê Thanh",
    "phoneNumber" : "0805021324",
    "email" : "lethanhpa@gmail.com",
    "address" : "VIETNAM",
    "birthday" : "2002/06/14"
}