POST http://localhost:9000/customers HTTP/1.1
content-type: application/json

{
    "firstName": "Nhàn",
    "lastName": "Phan Thị Thanh",
    "phoneNumber" : "0337215446",
    "email" : "phanthithanhnhan@gmail.com",
    "address" : "28 Phan Thanh",
    "birthday" : "1999/03/30"
}